# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
  
    pool:
      vmImage: 'vs2015-win2012r2'

    variables:
      buildConfiguration: 'Release'
      BuildPlatform: 'any cpu'
      workingDirectory: '$(Build.SourcesDirectory)/CoreWebAppAzure/src/CoreWebAppAzure'

    steps:
    - script: dotnet restore
      displayName: Restore
      workingDirectory: $(workingDirectory)
    - task: VSBuild@1
      inputs:
        solution: '**\\*.sln'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=False /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
        platform: 'Any CPU'
        configuration: 'Release'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
   

